import 'dart:convert';
import 'dart:io';

void main() {
  final configFile = File('branding/app_brand.json');
  if (!configFile.existsSync()) {
    stderr.writeln('Missing branding/app_brand.json');
    exitCode = 1;
    return;
  }

  final config =
      jsonDecode(configFile.readAsStringSync()) as Map<String, Object?>;
  final displayName = _requiredString(config, 'displayName');
  final bundleName = _requiredString(config, 'bundleName');
  final idLabel = _requiredString(config, 'idLabel');

  File('lib/src/config/app_brand.dart').writeAsStringSync('''
// Generated by tool/sync_app_brand.dart from branding/app_brand.json.
// Do not edit by hand.
abstract final class AppBrand {
  static const displayName = '${_dartString(displayName)}';
  static const bundleName = '${_dartString(bundleName)}';
  static const idLabel = '${_dartString(idLabel)}';
}
''');

  File('android/app/src/main/res/values/strings.xml').writeAsStringSync('''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/sync_app_brand.dart from branding/app_brand.json. -->
<resources>
    <string name="app_name">${_xmlText(displayName)}</string>
</resources>
''');

  File('ios/Flutter/AppBrand.xcconfig').writeAsStringSync('''
// Generated by tool/sync_app_brand.dart from branding/app_brand.json.
APP_DISPLAY_NAME=${_xcconfigValue(displayName)}
APP_BUNDLE_NAME=${_xcconfigValue(bundleName)}
''');
}

String _requiredString(Map<String, Object?> config, String key) {
  final value = config[key];
  if (value is String && value.trim().isNotEmpty) return value;
  throw FormatException('branding/app_brand.json must set non-empty "$key"');
}

String _dartString(String value) => value
    .replaceAll(r'\', r'\\')
    .replaceAll("'", r"\'")
    .replaceAll('\n', r'\n');

String _xmlText(String value) => value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

String _xcconfigValue(String value) => value.replaceAll('\n', ' ');
