// Generated by tool/sync_app_brand.dart from branding/app_brand.json.
// Do not edit by hand.
abstract final class AppBrand {
  static const displayName = 'FoxTalk';
  static const bundleName = 'foxtalk';
  static const idLabel = 'FoxTalk ID';
}
